version: 2

models:
  - name: dim_dates
    description: "Date dimension for time-based analysis"
    columns:
      - name: date_key
        description: "Surrogate key for the date"
        tests:
          - not_null
          - unique

  - name: dim_channels
    description: "Channel dimension with summary stats"
    columns:
      - name: channel_key
        description: "Surrogate key for the channel"
        tests:
          - not_null
          - unique
      - name: channel_name
        description: "Telegram channel name"
        tests:
          - not_null

  - name: fct_messages
    description: "Fact table with one row per Telegram message"
    columns:
      - name: message_id
        description: "Telegram message identifier"
        tests:
          - not_null
          - unique
      - name: channel_key
        description: "FK to dim_channels"
        tests:
          - not_null
          - relationships:
              to: ref('dim_channels')
              field: channel_key
      - name: date_key
        description: "FK to dim_dates"
        tests:
          - not_null
          - relationships:
              to: ref('dim_dates')
              field: date_key
      - name: view_count
        description: "Number of views"
      - name: forward_count
        description: "Number of forwards"
      - name: has_image
        description: "Whether the message has an image"
